# config/meta.yml
meta_product_name: "Coffeeisseur"
meta_title: "Coffeeisseur - What would you like to experience today?"
meta_description: "Relevant description"
meta_image: "og_image.jpeg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
